### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by hurricane2018** [BUPTLdy/MARTA-GAN#2]
Excuse me:
     when I run the following code. error appears:

feature = ConcatLayer(layer = [global_max1, global_max2, global_max3], name ='d/concat_layer1')
TypeError: __init__() got an unexpected keyword argument 'layer'

What should I do next ?

**Comment by BUPTLdy** [comment]
The Tensorlayer API has updated， maybe you can change as:
`feature = ConcatLayer([global_max1, global_max2, global_max3], name ='d/concat_layer1')`

**Comment by hurricane2018** [comment]
I have solved this problem. Thank you very much!
